# Matrices (Rank 2 tensors)

Characteristics of a matrix:

- Two-dimensional array of numbers
- Denoted in uppercase bold italics $\boldsymbol{X}$
- Arranged in a grid of rows and columns so that each element can be accessed by its row and column index
- Height is given priority ahead of width in notation, e.g. if $\boldsymbol{X}$ is a matrix with $m$ rows and $n$ columns, then the shape of $\boldsymbol{X}$ is $(m, n)$
- Individual elements of a matrix are denoted by uppercase, italic letters, e.g. the element in the $i$-th row and $j$-th column of matrix $\boldsymbol{X}$ is denoted by $X_{ij}$
- A colon represents *all elements* in a row or column, e.g. in the matrix $\boldsymbol{X}$ with shape $(3,2)$ :
    - the *left column* is denoted by $\boldsymbol{X}_{:, 1}$
    - the *middle row* is denoted by $\boldsymbol{X}_{2, :}$

$$\begin{bmatrix} x_{1,1} & x_{1,2} \\ x_{2,1} & x_{2,2} \\ x_{3,1} & x_{3,2} \end{bmatrix}$$

## Matrices with Python

In [1]:
import numpy as np
import torch
import tensorflow as tf

### Matrices with NumPy

In [2]:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X.shape

(3, 2)

In [4]:
X.size

6

In [5]:
# Select left column of matrix X (zero-indexed)
X[:,0]

array([25,  5,  3])

In [6]:
# Select middle row of matrix X:
X[1,:]

array([ 5, 26])

In [7]:
# Another slicing-by-index example:
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

### Matrices with PyTorch

In [8]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [9]:
X_pt.shape

torch.Size([3, 2])

Note that `.shape` and `size` are interchangeable in PyTorch:

In [10]:
X_pt.size()

torch.Size([3, 2])

In [11]:
X_pt[:,0]

tensor([25,  5,  3])

In [12]:
X_pt[1,:]

tensor([ 5, 26])

In [13]:
X_pt[0:2, 0:2]

tensor([[25,  2],
        [ 5, 26]])

### Matrices with TensorFlow

In [14]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [15]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [16]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [17]:
tf.size(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [18]:
X_tf[:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25,  5,  3])>

In [19]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>

In [20]:
X_tf[0:2, 0:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25,  2],
       [ 5, 26]])>