# Generic tensor notation

Characteristics of the generic tensor notation:

- Denoted in uppercase, bold, italics, sans-serif $\boldsymbol{\mathsfit{X}}$
- In a $4$-tensor $\boldsymbol{\mathsfit{X}}$, the element at position $(i,j,k,l)$ is denoted as $\boldsymbol{\mathsfit{X}}_{i,j,k,l}$


## Generating tensors

In [20]:
import torch
import tensorflow as tf

### Random tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [21]:
A = torch.rand(3, 4)

In [22]:
A

tensor([[0.5306, 0.3643, 0.4946, 0.5311],
        [0.4840, 0.8547, 0.5620, 0.2910],
        [0.2840, 0.1841, 0.1688, 0.6927]])

In [23]:
A.ndim

2

### Range of values

In [24]:
B = torch.arange(1, 11)
B

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
C = torch.arange(start=0, end=1000, step=77)
C

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

### Generating tensors-like

In [26]:
D = torch.zeros_like(B)
D

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Higher-rank tensors

In [27]:
images_pt = torch.zeros([32, 28, 28, 3])

In [28]:
images_pt.shape

torch.Size([32, 28, 28, 3])

In [29]:
images_pt.ndim

4

In [30]:
images_tf = tf.zeros([32, 28, 28, 3])

In [31]:
images_tf.shape

TensorShape([32, 28, 28, 3])

In [32]:
images_tf.ndim

4

## Tensor Data Types

In [33]:
E = torch.tensor([3.0, 6.0, 9.0])
E

tensor([3., 6., 9.])

In [34]:
E.dtype

torch.float32

In [35]:
F = torch.tensor([3.0, 6.0, 9.0],
                 dtype=None, # specify the data type
                 device=None, # specify the device used for computation
                 requires_grad=False # specify if gradients are required
                 )
F

tensor([3., 6., 9.])

It is important to note that operations between tensors may throw an error if:

- the tensors are not of the same data type
- the tensors are not of the same shape
- the tensors are not on the same device

In [36]:
G = F.type(torch.float16)
G

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
G.dtype

torch.float16

In [38]:
G.device

device(type='cpu')