# Eigendecomposition II

The eigendecomposition of a matrix $\boldsymbol{A}$, where:

- $V$ is the concatenation of all the eigenvectors of $\boldsymbol{A}$
- $\Lambda$ is a diagonal matrix $diag(\lambda)$

$$A = V \Lambda V^{-1}$$

The decomposition of a matrix into eigenvectors and eigenvalues reveals the underlying structure of the matrix.

In [1]:
import numpy as np
import torch

In [2]:
A = np.array([[4, 2], [-5, -3]])
A

array([[ 4,  2],
       [-5, -3]])

In [3]:
lambdas, V = np.linalg.eig(A)

In [4]:
V

array([[ 0.70710678, -0.37139068],
       [-0.70710678,  0.92847669]])

In [5]:
Vinv = np.linalg.inv(V)
Vinv

array([[2.3570226 , 0.94280904],
       [1.79505494, 1.79505494]])

In [6]:
Lambda = np.diag(lambdas)
Lambda

array([[ 2.,  0.],
       [ 0., -1.]])

In [7]:
np.dot(V, np.dot(Lambda, Vinv))

array([[ 4.,  2.],
       [-5., -3.]])

Eigendecomposition is not possible with all matrices. And in some cases where it is possible, the eigendecomposition involves complex numbers instead of straightforward real numbers.

In machine learning, however, we are typically working with real symmetric matrices, which can be conveniently and efficiently decomposed into real-only eigenvectors and real-only eigenvalues. If
$\boldsymbol{A}$ is a real symmetric matrix then, where:

- $\boldsymbol{Q}$ is an orthogonal matrix of eigenvectors
- $\boldsymbol{Q}^T$ is the transpose of $Q$

$A = Q \Lambda Q^T$

In [8]:
A = np.array([[2, 1], [1, 2]])
A

array([[2, 1],
       [1, 2]])

In [10]:
lambdas, Q = np.linalg.eig(A)
lambdas

array([3., 1.])

In [11]:
Lambda = np.diag(lambdas)
Lambda

array([[3., 0.],
       [0., 1.]])

In [12]:
Q

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

We can quickly demonstrate that $\boldsymbol{Q}$ is an orthogonal matrix because $\boldsymbol{Q}^T \boldsymbol{Q} = \boldsymbol{Q}\boldsymbol{Q}^T = \boldsymbol{I}$, where $\boldsymbol{I}$ is the identity matrix.

In [13]:
np.dot(Q.T, Q)

array([[1., 0.],
       [0., 1.]])

In [16]:
np.dot(Q, Q.T)

array([[1., 0.],
       [0., 1.]])

Decomposing the matrix $\boldsymbol{P}$ into its components $\boldsymbol{V}, \boldsymbol{\Lambda}$, and $\boldsymbol{V}^{-1}$:

In [17]:
P = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [19]:
eigenvalues, eigenvectors = torch.linalg.eig(P)

In [20]:
eigenvectors.real

tensor([[ 0.9511, -0.2386,  0.1626],
        [ 0.1218, -0.1924, -0.7705],
        [ 0.2837, -0.9519,  0.6163]])

In [21]:
eigenvalues.real

tensor([23.7644,  6.6684, -3.4328])

In [22]:
# $\Lambda V^{-1}$
Lambda = torch.diag(eigenvalues.real)
Lambda

tensor([[23.7644,  0.0000,  0.0000],
        [ 0.0000,  6.6684,  0.0000],
        [ 0.0000,  0.0000, -3.4328]])

Decomposing the symmetric matrix $\boldsymbol{S}$ into its components $\boldsymbol{Q}, \boldsymbol{\Lambda}$, and $\boldsymbol{Q}^T$ using PyTorch:

In [23]:
S = torch.tensor([[25, 2, -5], [2, -2, 1], [-5, 1, 4.]])
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [24]:
eigenvalues, eigenvectors = torch.linalg.eig(S)

In [25]:
eigenvectors.real

tensor([[ 0.9744,  0.1943, -0.1132],
        [ 0.0614,  0.2548,  0.9651],
        [-0.2163,  0.9473, -0.2363]])

In [26]:
eigenvalues.real

tensor([26.2361,  3.2435, -2.4796])

In [27]:
Lambda = torch.diag(eigenvalues.real)
Lambda

tensor([[26.2361,  0.0000,  0.0000],
        [ 0.0000,  3.2435,  0.0000],
        [ 0.0000,  0.0000, -2.4796]])