# The Trace Operator

The trace operator is useful to re-arrange linear algebra equation.

It's the sum of the diagonal elements of a square matrix:

$$\text{Tr}(\boldsymbol{A}) = \sum_{i} A_{i,i}$$

In [5]:
import numpy as np
import torch

In [3]:
A = np.array([[25, 2], [5, 4]])
A

array([[25,  2],
       [ 5,  4]])

In [4]:
np.trace(A)

29

The properties coming in handy to re-arrange equations are, for example:

- The trace of A is equal to the trace of A transposed $\text{Tr}(\boldsymbol{A}) = \text{Tr}(\boldsymbol{A}^T)$
- Assuming the matrix are multiplication compatible: $\text{Tr}(\boldsymbol{A}\boldsymbol{B}\boldsymbol{C}) = \text{Tr}(\boldsymbol{C}\boldsymbol{A}\boldsymbol{B}) = \text{Tr}(\boldsymbol{B}\boldsymbol{C}\boldsymbol{A})$

The trace operator can provide a convenient way to calculate the Frobenius norm of a matrix: $\|\boldsymbol{A}\|_F = \sqrt{\text{Tr}(\boldsymbol{AA}^T)}$

In [30]:
A = torch.tensor([[-1.,  2.],[ 3., -2.],[ 5.,  7.]])
A

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [31]:
torch.trace(A)

tensor(-3.)

In [32]:
torch.norm(A)

tensor(9.5917)

In [33]:
AT = A.T
AT

tensor([[-1.,  3.,  5.],
        [ 2., -2.,  7.]])

In [34]:
AAT = A @ AT
AAT

tensor([[ 5., -7.,  9.],
        [-7., 13.,  1.],
        [ 9.,  1., 74.]])

In [35]:
AAT_tr = torch.trace(AAT)
AAT_tr

tensor(92.)

In [36]:
torch.sqrt(AAT_tr)

tensor(9.5917)